version: "3.9"

services:
  server:
    image: yashparmar2055/server-app
    container_name: server
    ports:
      - "3001:3001"
    restart: always

  client:
    image: yashparmar2055/client-app
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: always
